routes: 
  - name: chat_openai
    route_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-3.5-turbo
      config:
        openai_api_key: $OPENAI_API_KEY
  - name: chat_mosaic_llama
    route_type: llm/v1/chat
    model:
      provider: mosaicml
      name: llama2-70b-chat
      config:
        mosaicml_api_key: $MOSAIC_API_KEY